### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by faheel** [ProAlgos/ProAlgos-Cpp#74]
## To-do
- [x] Reorganise the project
- [x] Write a Makefile to automate compilation, building and testing
- [x] Integrate with Travis CI and AppVeyor

### References
- https://github.com/faheel/Sample-Cpp-CI
